apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flask
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flask
    spec:
      containers:
      - name: flask
        ports:
          - containerPort: 5000
        image: "eltitans/flask:latest"
        env:
          - name: FLASK_APP
            value: "app"
          - name: FLASK_ENV
            value: "production"
          - name: DATABASE_URL
            value: "sqlite:///database.db"
        volumeMounts:
          - name: sqlite-storage
            mountPath: /instance/database
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: sqlite-pvc