
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-delete-sc  #We suppose this storage is already created (CICD)
  resources:
    requests:
      storage: 1Gi

